_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: true
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: true
element_name: url_field
time_limit: 0
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_access_support_form: false
  contact_message_campus_champions_form: false
  contact_message_careers_cyberteam_form: false
  contact_message_ccmnet_form: false
  contact_message_coco_form: false
  contact_message_connect_ci_form: false
  contact_message_feedback_form: false
  contact_message_great_plains_cyberteam_form: false
  contact_message_kentucky_cyberteam_form: false
  contact_message_mines_cyberteam_form: false
  contact_message_necyberteam_contact_form: false
  contact_message_northeast_cyberteam_form: false
  contact_message_personal_form: false
  contact_message_rmacc_cyberteam_form: false
  contact_message_sweeter_cyberteam_form: false
  contact_message_trecis_cyberteam_form: false
  contact_message_usrse_form: false
  node_access_active_resources_from_cid_form: false
  node_access_news_form: false
  node_access_organization_form: false
  node_affinity_group_form: false
  node_article_form: false
  node_blog_post_form: false
  node_blog_post_region__form: false
  node_community_events_form: false
  node_infrastructure_news_form: false
  node_match_engagement_form: false
  node_mentorship_engagement_form: false
  node_organization_form: false
  node_page_form: false
  node_peoplecardview_form: false
  node_peoplelistview_form: false
  node_press_release_form: false
  node_published_articles_form: false
  node_recommended_cider_form: false
  node_regional_about_form: false
  node_webform_form: false
  comment_comment_form: false
  comment_comment_node_article_form: false
  comment_comment_node_page_form: false
